/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_igo_mp3record_LameUtils */

#ifndef _Included_com_igo_mp3record_LameUtils
#define _Included_com_igo_mp3record_LameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_igo_mp3record_LameUtils
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_igo_mp3record_LameUtils_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_igo_mp3record_LameUtils
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_igo_mp3record_LameUtils_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_igo_mp3record_LameUtils
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_igo_mp3record_LameUtils_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_igo_mp3record_LameUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_igo_mp3record_LameUtils_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
